site_name: UC Berkeley CAS Documentation
theme: readthedocs
repo_url: https://github.com/bwood/ucberkeley_cas-7
extra_javascript:
  - extra.js
extra_css:
  - extra.css
pages:
  - Home: index.md
  - Configuration Details: configuration.md
  - Drush Commands: drush.md
  - Environments Configurations Module: envconf.md
  - LDAP Access: ldap_access.md
  - Release Notes: release_notes.md
  - FAQ: faq.md
markdown_extensions:
    - admonition:

